// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlkrxynawkruwznjrzng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsa3J4eW5hd2tydXd6bmpyem5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjMzMjYsImV4cCI6MjA2MTA5OTMyNn0.v7RRtcCnm8lXlTwr_nuys_KxwcimXcprvl0H24VmRY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);